### ISSUE TITLE
fire server crash?

### ISSUE THREAD

**Issue by ReasonGuy** [Geolykt/NMSless-Zenchantments#13]
Server keeps crashing saying this

19.07 17:09:39 [Server] ERROR ------------------------------
19.07 17:09:39 [Server] ERROR Current Thread: Server thread
19.07 17:09:39 [Server] ERROR PID: 43 | Suspended: false | Native: false | State: RUNNABLE
19.07 17:09:39 [Server] ERROR Stack:
19.07 17:09:39 [Server] ERROR zedly.zenchantments.enchantments.Fire.onBlockBreak(Fire.java:83)
19.07 17:09:39 [Server] ERROR zedly.zenchantments.evt.WatcherEnchant.lambda$onBlockBreak$0(WatcherEnchant.java:87)
19.07 17:09:39 [Server] ERROR zedly.zenchantments.evt.WatcherEnchant$$Lambda$6518/0x0000000801481840.test(Unknown Source)
19.07 17:09:39 [Server] ERROR zedly.zenchantments.CustomEnchantment.lambda$applyForTool$0(CustomEnchantment.java:246)
19.07 17:09:39 [Server] ERROR zedly.zenchantments.CustomEnchantment$$Lambda$5448/0x00000008015d5840.accept(Unknown Source)
19.07 17:09:39 [Server] ERROR java.base@11.0.6/java.util.LinkedHashMap.forEach(Unknown Source)
19.07 17:09:39 [Server] ERROR zedly.zenchantments.CustomEnchantment.applyForTool(CustomEnchantment.java:242)
19.07 17:09:39 [Server] ERROR zedly.zenchantments.evt.WatcherEnchant.onBlockBreak(WatcherEnchant.java:86)
19.07 17:09:39 [Server] ERROR com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor268.execute(Unknown Source)
19.07 17:09:39 [Server] ERROR app//org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
19.07 17:09:39 [Server] ERROR app//org.bukkit.plugin.EventExecutor$$Lambda$3821/0x0000000800da4440.execute(Unknown Source)
19.07 17:09:39 [Server] ERROR app//co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
19.07 17:09:39 [Server] ERROR app//org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
19.07 17:09:39 [Server] ERROR app//org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:324)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:283)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:224)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1389)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.PacketPlayInBlockDig.a(SourceFile:40)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.PacketPlayInBlockDig.a(SourceFile:10)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.PlayerConnectionUtils$$Lambda$5301/0x0000000801576840.run(Unknown Source)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
19.07 17:09:39 [Server] ERROR app//net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$3021/0x00000008008cd040.run(Unknown Source)
19.07 17:09:39 [Server] ERROR java.base@11.0.6/java.lang.Thread.run(Unknown Source)
19.07 17:09:39 [Server] ERROR ------------------------------

**Comment by Geolykt** [comment]
Version?
Bukkit implementation?
Type of crash?
Datapacks?
Activity before crash?

Nonetheless, in 90% of cases this is already fixed or another plugin's fault.
Line 83 of the Fire enchantment source file is in the 1.15 edition a bracket and in the dev-geolykt branch a harmless instruction in a harmless while loop.
Update and provide more details

**Comment by ReasonGuy** [comment]
sorry for the lack of detail
version 1.16
using no datapacks, just a couple other stable plugins
the error only occured when a player used fire and the whole server crashed.

I disabled the fire enchant and that error went away.

**Comment by Geolykt** [comment]
That's wired, did you compile the plugin yourself? I Recall having a bug that would create infinite Stone, but it was fixed later.

Otherwise, try disabling the softcoded patch / enable the hardcoded fire enchantment

**Comment by Geolykt** [comment]
I sadly can't do anything here, it might be plattform dependent code, might be something else, sorry. But it looks as if another plugin is involved in this (logging plugins perhaps) anyways, if anyone can recreate this, then feel free to

**Comment by Geolykt** [comment]
Was able to reproduce this. It always occours when a non-smeltable block gets mined by a fire enchanted tool. The exact reason to this is that the Itemstack size of AIR is 0, which results in an infinite loop and a crash or OOM. I'll likely update the code shortly to fix this
