### ISSUE TITLE
permission lacking for /ench command

### ISSUE THREAD

**Issue by ReasonGuy** [Geolykt/NMSless-Zenchantments#14]
Having no permission nodes enabled for any player under ench
yet all non op players are able to use /ench enchantment level
basically allowing them to get any level zencahntment freely

**Comment by Geolykt** [comment]
I think I fixed it with the latest commut, although I did Not check that, in that Case, reopen the issue. Anyways, thanks for reporting that pretty severe bug <3

**Comment by ReasonGuy** [comment]
yeah sadly because of that since I run an anarchy server, about a dozen players hid a few hundred items that had maxed out zenchantments.
Meaning after a half a year of using zenchantments we had to remove them >.<

Hope things work out for you while working on zenchantments going forward :D
