### ISSUE TITLE
Suggestion:Paper Support

### ISSUE THREAD

**Issue by austin652** [Geolykt/NMSless-Zenchantments#16]
I'm so glad that someone has updated this plugin while the main dev is unable to. I was glad to find this and would love to use it but it doesn't work on paper or at least not on paper 1.16.2. 
(Sorry if this is not the place for this)

**Comment by Geolykt** [comment]
This is pretty odd. Please report this issue to Paper (unless that'll report it as a logical issue on my side) but the paper team must get their shit together to maintain compatibillity with spigot plugins, I aint coding things twice

**Comment by Geolykt** [comment]
This seems to be wrongly labeled.
In reality it was a frickup by me that made so no things work.
i'm deeply sorry by this. this bug will be updated ASAP

**Comment by Geolykt** [comment]
@austin652 I fixed the underlying problem, while it looks as if the bind enchantment (the only one I tested) works a bit bad, other than that it works as intended and the OOM is no more. Feel free to use the https://github.com/Geolykt/NMSless-Zenchantments/releases/tag/v1.9.1 now

**Comment by austin652** [comment]
Great! thank you
