### ISSUE TITLE
Allow the usage of entity placeholders in the "/ench give" command

### ISSUE THREAD

**Issue by Geolykt** [Geolykt/NMSless-Zenchantments#2]
Is there a way to select "@a"/"@p"/"@r" as a player? When i type something along the lines of "/ench give @a BOW missile 1"
but it says that player is not online.

**Comment by tinkeringmatt** [comment]
for testing to confirm it's the plugin failing to perform the action
try
@s 
It applies the command to the entity executing the command

**Comment by Geolykt** [comment]
I know, the whole plugin doesn't support these entity placeholders
