### ISSUE TITLE
1.16.1: Zenchantments enchanted items can be combined to make a level 1 unbreaking item

### ISSUE THREAD

**Issue by Geolykt** [Geolykt/NMSless-Zenchantments#4]
See https://github.com/Zedly/Zenchantments/issues/40 for more info

**Comment by chrismwiggs** [comment]
Issue is still happening with even with [eddcf5e](https://github.com/Geolykt/Zenchantments/commit/eddcf5e5cb069d91521ebd1a3d2699114d5714ac), on 1.15.2. Haven't tried 1.16.1 though.

**Comment by Geolykt** [comment]
Thanks @chrismwiggs , I reopened the issue and I'll see why this occour, however I cannot imagine to why this issue occurs since there is code to prevent that in place. Does the console report anything?

**Comment by tinkeringmatt** [comment]
Tried on 1.16.1
the unbreaking bug is still present in addition to the issue with enchants not working and deleting themself after relogging in.

Using paper 1.16.1 latest version

**Comment by Geolykt** [comment]
I'm currently more keen on getting it to work in 1.16.1, although it looks as if this is an impossible task. I think the bug appears when one item doesn't have any zenchantments and unbreaking and the other one has a single zenchantment (and thus unbreaking 0)? In that case it could be likely that no code was written for this

**Comment by tinkeringmatt** [comment]
I think your method of replacing the hidden lore with nbt tags will be a much smarter method.
I'll ask will there be a way to auto convert old lore data if the plugin runs across it?

**Comment by Geolykt** [comment]
@tinkeringmatt It isn't really doable without creating major lag. However, I could make so that the plugin automatically converts when the item gets a new enchantment and when the player chooses to perform a command. While it is much smarter and easier to implement and maintain codewise, it will be harder for other plugins to support this plugin, although I don't know, perhaps most plugins already account for NBT

**Comment by tinkeringmatt** [comment]
@Geolykt 
Plus I think there's a problem
Because when logging out old zenchant hiddenlore info is erased from a player inv items.
So it would have to be in version 1.15
however the changes you're making are specifically for version 1.16

So I suspect I'll need to figure out another manual method instead

**Comment by tinkeringmatt** [comment]
@Geolykt 
Side note
Love your work
Thank you so much for updating this :D

**Comment by Geolykt** [comment]
@tinkeringmatt That's strange, never heard of such stuff outside of other plugins not working as intended. Also, most changes do support 1.15.2 and likely older version too, you just need to manually build the project in 1.15.2 and remove any invalid varaible (such as warped nylium) as well as change the API version in the plugin.yml file.
If the issue also persists here, feel free to create an issue

**Comment by Geolykt** [comment]
@chrismwiggs 
@tinkeringmatt 
Hello, I was unable to reproduce the issue, please attach any information on how to replicate the issue on the latest build in order for me to patch it
