### ISSUE TITLE
Siphon giving errors

### ISSUE THREAD

**Issue by tinkeringmatt** [Geolykt/NMSless-Zenchantments#8]
Looks like that siphon is trying to set a higher hp value than the players maxhp attribute would allow.
Needs to do a check maxhp before setting the hp change

10.07 13:18:42 [Server] WARN at java.base/java.lang.Thread.run(Unknown Source)
10.07 13:18:53 [Server] WARN java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 21.0. (attribute base value: 20.0, player: iOmlForce)
10.07 13:18:53 [Server] WARN at org.bukkit.craftbukkit.v1_16_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:115)
10.07 13:18:53 [Server] WARN at zedly.zenchantments.enchantments.Siphon.onEntityHit(Siphon.java:44)
10.07 13:18:53 [Server] WARN at zedly.zenchantments.evt.WatcherEnchant.lambda$onEntityHit$6(WatcherEnchant.jav...
...

**Comment by Geolykt** [comment]
Thanks for reporting the issue, I will attempt to recreate it
